#!/bin/bash

#Colors for when I eventually add them to the verbose
NC='\033[0m' # No Color
ACCENT='\033[1;31m'

while getopts bhrf flag
do
    case "${flag}" in
    	b) backup="True";;
		h) help="True";;
		r) rename="True";;
		f) files="True";;
    esac
done

if [[ "$help" == "True" ]]; then
	echo -e "Usage: ./config [-b]

[I] Install dotfiles to your system (the dotfiles folder needs to be in your home directory)

Optional arguments:
  -b,         Creates a backup of your current dotfiles and stores it in ~/.backup
  -r,         Renames default directory with shorter names and deletes useless ones.
  -f,         Copies various files such as a few wallpapers, grub-theme installer to ~/pics.
  -h,         Displays this message and exit. \n"
 else

 	#Validation
 	echo "Are you sure you want to proceed? To cancel press Ctrl+C or press ENTER to continue " && read answer
 	
 	# Backup process
	[[ -d $HOME/.backup ]] && echo -e "\nA previous backup (~/.backup) has been found, it will be overwritten. To cancel press Ctrl+C or press ENTER to continue " && read answer
	[[ "$backup" == "True" ]] && echo "Backing up to ~/.backup" && sudo rm -rf $HOME/.backup && mkdir $HOME/.backup &&sudo cp -p -r $HOME/.config/ $HOME/.backup/.config && echo "Done: .config/ " && sudo cp -p -r /etc/ $HOME/.backup/etc && echo "Done: etc/ " && sudo cp -p $HOME/{.Xresources,.bashrc,.bash_profile,.profile} $HOME/.backup/ && echo "Done: dotfiles \n"


	# Renames default directory with shorter names and deletes useless ones
	[[ "$rename" == "True" ]] && mv $HOME/Downloads $HOME/dl && mv $HOME/Documents $HOME/docs && mv $HOME/Pictures $HOME/pics
	[[ -d $HOME/Public ]] && rm -rf $HOME/Public
	[[ -d $HOME/Templates ]] && rm -rf $HOME/Templates
	[[ -d $HOME/Videos ]] && rm -rf $HOME/Videos
	[[ -d $HOME/Music ]] && rm -rf $HOME/Music
	[[ -d $HOME/Desktop ]] && rm -rf $HOME/Desktop
	
	# Copies various files such a few wallpapers, grub-theme installer to ~/pics
	[[ "$files" == "True" ]] && cp -r $HOME/dotfiles/files/* $HOME/pics/
	
	# Symlink .config files
	for entry in ".config"/*
	do
		rm -rf "$HOME/$entry" && echo "Deleted $HOME/$entry"
		ln -s "$HOME/dotfiles/$entry" "$HOME/$entry" && echo -e "Created symlink with $entry \n"
	done


	# Symlink /etc files (since there is a few files I do it manually for now)
	
	#Pulse
	[[ -d /etc/pulse ]]  && echo "Found /etc/pulse" && sudo rm -rf /etc/pulse && echo "Deleted /etc/pulse"
	sudo ln -s $HOME/dotfiles/etc/pulse /etc/ && echo -e "Created symlink with etc/pulse \n"

	#Pacman.d
	[[ -d /etc/pacman.d/hooks ]]  && echo "Found /etc/pacman.d/hooks" && sudo rm -rf /etc/pacman.d/hooks && echo "Deleted /etc/pacman.d/hooks"
	sudo ln -s $HOME/dotfiles/etc/pacman.d/hooks /etc/pacman.d && echo -e "Created symlink with etc/pacman.d/hooks \n"

	#Slick-greeter
	for entry in "etc/lightdm"/*
	do
		sudo rm -rf "/$entry" && echo "/$entry"
		sudo ln -s "$HOME/dotfiles/$entry" "/$entry" && echo -e "Created symlink with $entry \n"
	done
	sudo cp $HOME/dotfiles/files/slick-greeter/* /usr/share/slick-greeter/ #Copies arch.png and slick-greeter.png
	
	#for entry in "etc"/*
	#do
	#	sudo rm -rf /"$entry" && echo Deleted /"$entry"
	#	sudo ln -s "$HOME"/dotfiles/$entry /"$entry" && echo -e "Created symlink with $entry \n"
	#done


	# Symlink myfonts folder
	[[ -d /usr/share/fonts/myfonts ]]  && echo "Found /usr/share/fonts/myfonts" && sudo rm -rf /usr/share/fonts/myfonts && echo "Deleted /usr/share/fonts/myfonts"
	sudo ln -s $HOME/dotfiles/myfonts /usr/share/fonts/ && echo -e "Created symlink with myfonts \n" && fc-cache

	# Symlink scripts folder
	[[ -d $HOME/scripts ]]  && echo "Found ~/scripts" && rm -rf $HOME/scripts && echo "Deleted ~/scripts"
	ln -s $HOME/dotfiles/scripts $HOME  && echo -e "Symlinked scripts folder \n"

	# Symlink .bashrc
	[[ -f $HOME/.bashrc ]] && echo "Found .bashrc" && rm $HOME/.bashrc && echo "Deleted .bashrc"
	ln -s $HOME/dotfiles/.bashrc $HOME && echo -e "Symlinked .bashrc \n" && source $HOME/.bashrc

	# Symlink .bash_profile
	[[ -f $HOME/.bash_profile ]] && echo "Found .bash_profile" && rm $HOME/.bash_profile && echo "Deleted .bash_profile"
	ln -s $HOME/dotfiles/.bash_profile $HOME && echo -e "Symlinked .bash_profile \n" && source $HOME/.bash_profile

	# Symlink .profile
	[[ -f $HOME/.profile ]] && echo "Found .profile" && rm $HOME/.profile && echo "Deleted .profile"
	ln -s $HOME/dotfiles/.profile $HOME && echo -e "Symlinked .profile \n" && source $HOME/.profile

	# Symlink .Xresources
	[[ -f $HOME/.Xresources ]] && echo "Found .Xresources" && rm $HOME/.Xresources && echo "Deleted .Xresources"
	ln -s $HOME/dotfiles/.Xresources $HOME && echo "Symlinked .Xresources " && xrdb $HOME/.Xresources
	
	# Applies default theme 
	$HOME/scripts/pywal -i $HOME/dotfiles/files/walls/darkplant.jpg -a 90 -p
fi