#!/bin/bash

# Colors for when I eventually add them to the verbose
NC='\033[0m' #  No Color
C1='\033[1;31m'

while getopts h flag
do
    case "${flag}" in
		h) help="True";;
    esac
done

if [[ "$help" == "True" ]]; then
	echo -e "Usage: ./packages [-b]

[I] Install all necessary packages and remove unnecessary ones on the system

Optional arguments:
  -h,         Displays this message. \n"
else

	# Removes bloat
	echo "\n[.] Removing bloat"
	sudo pacman -Rd --nodeps pcmanfm nitrogen palemoon-bin picom vlc clipit

	#  Add Sublime Text repo
	sudo curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
	sudo echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf && echo "[.] Added Sublime Text repository"

	# Updates system
	echo "[.] Updating existing packages"
 	sudo pacman -Syuu

 	# Official Arch repo packages
 	echo "[.] Installing packages"
 	sudo pacman -S --needed sublime-text gufw xfce4-clipman-plugin xfce4-screenshooter youtube-dl timeshift pavucontrol thunar libratbag curlgnome-disk-utility baobab python cmatrix xcb-util-xrm tumbler python-pywal imagemagick feh slop neofetch firefox pulseaudio rofi playerctl wmctrl xfce4-power-manager polybar redshift fzy trash-cli hidapi g810-led-git
	
	# Copies st to ~/ and installs it
	echo "[.] Installing Suckless Terminal"
	cp -r $HOME/dotfiles/st $HOME/
	cd $HOME/st && sudo rm config.h && sudo make clean install

	# Python packages
	echo "[.] Installing pip packages"
	sudo pip install i3-py pywalfox powerline-shell

	# AUR packages (long compiling)
	echo "[.] Installing AUR packages"
	aurlist=(picom-ibhagwan-git mimi-git ytop progress-git spicetify-cli cava expressvpn spotify espanso oomox scrcpy
	)
	tobeinstalled=""

	echo "[.] Checking for already installed packages..."
	for i in ${aurlist[@]};do
		[ -z $(pamac list -i | cut -d' ' -f1 | grep -w "$i") ] && tobeinstalled+="$i "
	done

	pamac build $tobeinstalled

 	
 	#  Misc

 	# Disable dunst autostart via systemd so that it's started by i3 with Xresources colors
 	echo "[.] Disabling Dunst's autostartup"
 	systemctl --user disable dunst
	systemctl --user stop dunst


	echo "Now run ./config to finish the dotfiles install
	Press ENTER to exit"
	read answer
	
fi