#!/bin/bash

NC='\033[0m' # No Color
ACCENT='\033[1;31m'

while getopts h flag
do
    case "${flag}" in
		h) help="True";;
    esac
done

if [[ "$help" == "True" ]]; then
	echo -e "Usage: ./packages [-b]

[I] Install all necessary packages and remove unnecessary ones on the system

Optional arguments:
  -h,         Displays this message. \n"
else

	#Removes bloat
	echo "[.] Removing bloat"
	sudo pacman -Rd --nodeps nitrogen palemoon-bin picom

	#Updates system
	echo "[.] Updating existing packages"
 	sudo pacman -Syuu

 	echo "[.] Installing packages"
 	sudo pacman -S xcb-util-xrm tumbler xfce4-screenshooter python-pywal imagemagick feh slop neofetch brave pulseaudio rofi playerctl wmctrl xfce4-power-manager polybar redshift
 	
 	#Picom Fork with kawase blur and rounder corners
	cd $HOME/Downloads && git clone https://github.com/ibhagwan/picom-ibhagwan-git && cd picom-ibhagwan-git && makepkg -si

	#Sublime Text
	sudo curl -O https://download.sublimetext.com/sublimehq-pub.gpg && sudo pacman-key --add sublimehq-pub.gpg && sudo pacman-key --lsign-key 8A8F901A && rm sublimehq-pub.gpg
	sudo echo -e "\n[sublime-text]\nServer = https://download.sublimetext.com/arch/stable/x86_64" | sudo tee -a /etc/pacman.conf
	sudo pacman -Syu sublime-text

	#Takes a long time to compile so they are at the end
 	pamac build spotify espanso oomox

 	
 	# Misc

 	#Disable dunst autostart via systemd so that it's started by i3 with Xresources colors
 	systemctl --user disable dunst
	systemctl --user stop dunst


	echo "Install dotfiles? "
	read answer
	if [ "$answer" == "y" ]; then
		$HOME/dotfiles/config
	else
		:
	fi
fi