#!/bin/bash

NC='\033[0m' # No Color
C1='\033[1;31m'

while getopts h flag; do
  case "${flag}" in
  h) help="True" ;;
  esac
done

[ "$help" = "True" ] && echo -e "\nUsage: ./packages

Install all necessary packages and remove unnecessary ones on the system

Optional arguments:
  -h,         Displays this message. \n" && exit

# REMOVE BLOAT
echo "\n[.] Removing bloat"
sudo pacman -Rd --nodeps pcmanfm nitrogen palemoon-bin picom vlc clipit

# UPDATE SYSTEM
echo "[.] Updating existing packages"
sudo pacman -Syuu

# ARCH REPO PACKAGES
echo "[.] Installing packages"
sudo pacman -S --needed gufw xfce4-clipman-plugin xfce4-screenshooter youtube-dl timeshift pavucontrol thunar libratbag curlgnome-disk-utility baobab python xcb-util-xrm tumbler python-pywal imagemagick feh slop neofetch firefox pulseaudio rofi playerctl wmctrl xfce4-power-manager polybar redshift fzy trash-cli hidapi xorg-fonts-alias-misc ueberzug pulseaudio-equalizer protonvpn-linux-gui anydesk-bin audacity code noto-fonts-emoji

# SUCKLESS TERMINAL
echo "[.] Installing Suckless Terminal"
cp -r $HOME/dotfiles/st $HOME/
cd $HOME/st && sudo rm config.h && sudo make clean install

# PYTHON PACKAGES
echo "[.] Installing pip packages"
sudo pip install i3-py powerline-shell

# AUR PACKAGES (LONG COMPILING)
echo "[.] Installing AUR packages"
aurlist=(picom-ibhagwan-git mimi-git ytop spicetify-cli cavaspotify espanso oomox scrcpy
)

tobeinstalled=""

echo "[.] Checking for already installed packages..."
for i in ${aurlist[@]}; do
  [ -z $(pamac list -i | cut -d' ' -f1 | grep -w "$i") ] && tobeinstalled+="$i "
done

pamac build $tobeinstalled

# EXIT
echo "Now run ./config to finish the dotfiles install
	Press ENTER to exit"
read answer
