#!/bin/bash

script_folder="$HOME/scripts"
script_file="$script_folder/$1"

if [ -e $script_file ]; then
	echo "File already exists"
else
	echo "#!/bin/bash" > $script_file
	chmod +x $script_file
	printf "Open the script in Sublime? "
	read answer
	if [ "$answer" == "y" ]; then
		subl $script_file
		wmctrl -s 2
	fi
fi
