#!/bin/bash
#CONFIG EDIT

editor="code"

file=$(
  find ~/dotfiles/.config/ -type f -iname "config*" ! -iname "*.code" \
  | sed 's/.*config\///g' \
  | fzy -l 15
)
file="$HOME/.config/$file"

! [ -z $file ] && $editor $file && wmctrl -s 2

