#!/bin/bash
if [[ -z $1 ]];then

	initializeANSI()
	{
	 esc=""

	  blackf="${esc}[31m";   redf="${esc}[31m";    greenf="${esc}[32m"
	  yellowf="${esc}[33m"   bluef="${esc}[34m";   purplef="${esc}[35m"
	  cyanf="${esc}[36m";    whitef="${esc}[37m"

	  blackb="${esc}[40m";   redb="${esc}[41m";    greenb="${esc}[42m"
	  yellowb="${esc}[43m"   blueb="${esc}[44m";   purpleb="${esc}[45m"
	  cyanb="${esc}[46m";    whiteb="${esc}[47m"

	  boldon="${esc}[1m";    boldoff="${esc}[22m"
	  italicson="${esc}[3m"; italicsoff="${esc}[23m"
	  ulon="${esc}[4m";      uloff="${esc}[24m"
	  invon="${esc}[7m";     invoff="${esc}[27m"

	  reset="${esc}[0m"
	}

	initializeANSI

	cat << EOF

	    ${boldon}${blackf} ██████${reset}
	   ${boldon}${blackf}██${reset}██${reset}${bluef}██${reset}${boldon}${blackf}██${reset}${bluef}██${reset}
	   ${boldon}${blackf}██${reset}██${bluef}██${reset}${boldon}${blackf}██${reset}${bluef}██${reset}
	   ${boldon}${blackf}██████${reset}${purplef}██████${reset}
	   ${boldon}${blackf}████${reset}████${boldon}${blackf}██${reset}
	 ${boldon}${blackf}████${reset}████████${boldon}${blackf}██${reset}
	 ${boldon}${blackf}████${reset}████████${boldon}${blackf}██${reset}
	 ${boldon}${blackf}████${reset}████████${boldon}${blackf}██${reset}
	   ${boldon}${blackf}████${reset}████${boldon}${blackf}██${reset}
	  ${boldon}${blackf}███${reset}${purplef}███   ████${reset}

EOF
fi







if [[ $1 == "1" ]]; then
	T='*'   # The test text

	echo -e "\n             40m 41m 42m 43m\
	 44m 45m 46m 47m";

	for FGs in '    m' '   1m' '  30m' '1;30m' '  31m' '1;31m' '  32m' \
	           '1;32m' '  33m' '1;33m' '  34m' '1;34m' '  35m' '1;35m' \
	           '  36m' '1;36m' '  37m' '1;37m';
	  do FG=${FGs// /}
	  echo -en " $FGs \033[$FG  $T  "
	  for BG in 40m 41m 42m 43m 44m 45m 46m 47m;
	    do echo -en "$EINS \033[$FG\033[$BG $T \033[0m";
	  done
	  echo;
	done
	echo
fi


if [[ $1 == "2" ]]; then
	xdef="$HOME/.Xresources"
	colors=( $( sed -re '/^!/d; /^$/d; /^#/d; s/(\*color)([0-9]):/\10\2:/g;' $xdef | grep 'color[01][0-9]:' | sort | sed  's/^.*: *//g' ) )

	echo -e "\e[1;37m 
 Black    Red      Green    Yellow   Blue     Magenta   Cyan    White   
 ──────────────────────────────────────────────────────────────────────\e[0m"
	for i in {0..7}; do echo -en "\e[$((30+$i))m ${colors[i]} \e[0m"; done
	echo
	for i in {8..15}; do echo -en "\e[1;$((22+$i))m ${colors[i]} \e[0m"; done
	echo -e "\n"
fi

if [[ $1 == "3" ]]; then
	xdef="$HOME/.Xresources"

	colors=( $( sed -re '/^!/d; /^$/d; /^#/d; s/(\*color)([0-9]):/\10\2:/g;' $xdef | grep 'color[01][0-9]:' | sort | sed  's/^.*: *//g' ) 
	)

	echo
	for i in {0..7}; do echo -en "\e[$((30+$i))m ${colors[i]} \u2588\u2588 \e[0m"; done
	echo
	for i in {8..15}; do echo -en "\e[1;$((22+$i))m ${colors[i]} \u2588\u2588 \e[0m"; done
	echo -e "\n"
fi

if [[ $1 == "4" ]]; then
		f=3 b=4
		for j in f b; do
		  for i in {0..7}; do
		    printf -v $j$i %b "\e[${!j}${i}m"
		  done
		done
		bld=$'\e[1m'
		rst=$'\e[0m'
		inv=$'\e[7m'

	cat << EOF
	$rst
	 $f3  ▄███████▄                $f1  ▄██████▄    $f2  ▄██████▄    $f4  ▄██████▄    $f5  ▄██████▄    $f6  ▄██████▄    
	 $f3▄█████████▀▀               $f1▄$f7█▀█$f1██$f7█▀█$f1██▄  $f2▄█$f7███$f2██$f7███$f2█▄  $f4▄█$f7███$f4██$f7███$f4█▄  $f5▄█$f7███$f5██$f7███$f5█▄  $f6▄██$f7█▀█$f6██$f7█▀█$f6▄
	 $f3███████▀      $f7▄▄  ▄▄  ▄▄   $f1█$f7▄▄█$f1██$f7▄▄█$f1███  $f2██$f7█ █$f2██$f7█ █$f2██  $f4██$f7█ █$f4██$f7█ █$f4██  $f5██$f7█ █$f5██$f7█ █$f5██  $f6███$f7█▄▄$f6██$f7█▄▄$f6█
	 $f3███████▄      $f7▀▀  ▀▀  ▀▀   $f1████████████  $f2████████████  $f4████████████  $f5████████████  $f6████████████  
	 $f3▀█████████▄▄               $f1██▀██▀▀██▀██  $f2██▀██▀▀██▀██  $f4██▀██▀▀██▀██  $f5██▀██▀▀██▀██  $f6██▀██▀▀██▀██
	 $f3  ▀███████▀                $f1▀   ▀  ▀   ▀  $f2▀   ▀  ▀   ▀  $f4▀   ▀  ▀   ▀  $f5▀   ▀  ▀   ▀  $f6▀   ▀  ▀   ▀ 
	$bld
	 $f3  ▄███████▄                $f1  ▄██████▄    $f2  ▄██████▄    $f4  ▄██████▄    $f5  ▄██████▄    $f6  ▄██████▄    
	 $f3▄█████████▀▀               $f1▄$f7█▀█$f1██$f7█▀█$f1██▄  $f2▄█$f7█ █$f2██$f7█ █$f2█▄  $f4▄█$f7█ █$f4██$f7█ █$f4█▄  $f5▄█$f7█ █$f5██$f7█ █$f5█▄  $f6▄██$f7█▀█$f6██$f7█▀█$f6▄
	 $f3███████▀      $f7▄▄  ▄▄  ▄▄   $f1█$f7▄▄█$f1██$f7▄▄█$f1███  $f2██$f7███$f2██$f7███$f2██  $f4██$f7███$f4██$f7███$f4██  $f5██$f7███$f5██$f7███$f5██  $f6███$f7█▄▄$f6██$f7█▄▄$f6█
	 $f3███████▄      $f7▀▀  ▀▀  ▀▀   $f1████████████  $f2████████████  $f4████████████  $f5████████████  $f6████████████  
	 $f3▀█████████▄▄               $f1██▀██▀▀██▀██  $f2██▀██▀▀██▀██  $f4██▀██▀▀██▀██  $f5██▀██▀▀██▀██  $f6██▀██▀▀██▀██
	 $f3  ▀███████▀                $f1▀   ▀  ▀   ▀  $f2▀   ▀  ▀   ▀  $f4▀   ▀  ▀   ▀  $f5▀   ▀  ▀   ▀  $f6▀   ▀  ▀   ▀ 
	$rst
EOF
fi



if [[ $1 == "5" ]]; then
	initializeANSI()
	{
	  esc=""

	  blackf="${esc}[30m";   redf="${esc}[31m";    greenf="${esc}[32m"
	  yellowf="${esc}[33m"   bluef="${esc}[34m";   purplef="${esc}[35m"
	  cyanf="${esc}[36m";    whitef="${esc}[37m"
	  
	  blackb="${esc}[40m";   redb="${esc}[41m";    greenb="${esc}[42m"
	  yellowb="${esc}[43m"   blueb="${esc}[44m";   purpleb="${esc}[45m"
	  cyanb="${esc}[46m";    whiteb="${esc}[47m"

	  boldon="${esc}[1m";    boldoff="${esc}[22m"
	  italicson="${esc}[3m"; italicsoff="${esc}[23m"
	  ulon="${esc}[4m";      uloff="${esc}[24m"
	  invon="${esc}[7m";     invoff="${esc}[27m"

	  reset="${esc}[0m"
	}

	# note in this first use that switching colors doesn't require a reset
	# first - the new color overrides the old one.

	initializeANSI

	cat << EOF 

	${boldon}${redf} █   █ ${reset} ${boldon}${greenf}█   █ ${reset} ${boldon}${yellowf}█   █ ${reset} ${boldon}${bluef}█   █ ${reset} ${boldon}${purplef}█   █ ${reset} ${boldon}${cyanf}█   █ ${reset} 
	${boldon}${redf}  ■ ■  ${reset} ${boldon}${greenf} ■ ■  ${reset} ${boldon}${yellowf} ■ ■  ${reset} ${boldon}${bluef} ■ ■  ${reset} ${boldon}${purplef} ■ ■  ${reset} ${boldon}${cyanf} ■ ■  ${reset}
	${boldon}${redf}  =■=  ${reset} ${boldon}${greenf} =■=  ${reset} ${boldon}${yellowf} =■=  ${reset} ${boldon}${bluef} =■=  ${reset} ${boldon}${purplef} =■=  ${reset} ${boldon}${cyanf} =■=  ${reset}
	 
	${redf} █=@=█ ${reset} ${greenf}█=@=█ ${reset} ${yellowf}█=@=█ ${reset} ${bluef}█=@=█ ${reset} ${purplef}█=@=█ ${reset} ${cyanf}█=@=█ ${reset}
	${redf}  ■ ■  ${reset} ${greenf} ■ ■  ${reset} ${yellowf} ■ ■  ${reset} ${bluef} ■ ■  ${reset} ${purplef} ■ ■  ${reset} ${cyanf} ■ ■  ${reset}
	${redf}  =■=  ${reset} ${greenf} =■=  ${reset} ${yellowf} =■=  ${reset} ${bluef} =■=  ${reset} ${purplef} =■=  ${reset} ${cyanf} =■=  ${reset} 

EOF
fi