#!/usr/bin/env python
import sys
import pyautogui
import time
import re
import gi
gi.require_version("Gdk", "3.0")
from gi.repository import Gdk

def PixelAt(x, y):
  w = Gdk.get_default_root_window()
  pb = Gdk.pixbuf_get_from_window(w, x, y, 1, 1)
  return pb.get_pixels()

def rgb_to_hex(rgb):
	red = rgb[0]
	green = rgb[1]
	blue = rgb[2]
	return '#%02x%02x%02x' % (red,green,blue)


print("Put your mouse on the desired color:")
for i in range(5,0,-1):
	time.sleep(0.5)
	print(i, end='', flush=True)
	time.sleep(0.25)	
	print(".", end='', flush=True)
	time.sleep(0.25)
	print(".", end='', flush=True)
time.sleep(1)
print("  SNAP!")

coords = str(pyautogui.position())
xy = re.findall("\d+", coords)
x = int(xy[0])
y = int(xy[1])
print(rgb_to_hex(tuple(PixelAt(x, y))))