#!/bin/bash
[ -z $1 ] && pid=$(ps -e -o command,pid | sed '/\[.*\s/d; /COMMAND.*$/d' | pmenu -p "> " )
[ "$1" == "rofi" ] && pid=$(ps -e -o command,pid | sed '/\[.*\s/d; /COMMAND.*$/d' | rofi -dmenu -i -p "Program to kill")
! [ -z $pid ] && kill -9 $pid

