#!/bin/bash

i3-msg "workspace 1: ; append_layout ~/.config/i3/workspace_1.json"

nc='\033[0m' # No Color
accent='\033[1;31m'
accent2='\033[1;37m'
bold=$(tput bold)
normal=$(tput sgr0)

urxvt -name ranger -e sh -c "ranger;bash" &
urxvt -name main -hold -e sh -c "
echo -e '$bold$accent[ Welcome Back! How are you today $accent2$USER$accent ? ]$nc$bold';
curl wttr.in/Iskele?format="~+Weather+:+%t+%C+~";
echo "";
neofetch;
bash" &
urxvt -name htop -e sh -c "htop;bash" &