#!/bin/bash
if [ "$1" == "loop" ]; then
	while true; do
		[ "$2" == "time" ] && toilet -f Big.flf $(date +"%I : %M %p") | lolcat && sleep 60s || toilet -f 3d.flf "$2"| lolcat && sleep 0.5s
	done
else
	[ "$1" == "time" ] && toilet -f Big.flf $(date +"%I : %M %p") | lolcat || toilet -f 3d.flf "$1"| lolcat
fi
