#!/bin/bash

cat ~/.config/rofi/nerd-font-cheatsheet.md | rofi -dmenu -font "Fira Code Nerd Font 15" -p "NF Cheatsheet" -fg "#ffffff" -columns 2 -width 40 | cut -d" " -f1 | tr '\n' ' ' | xclip -selection clipboard
