#!/bin/bash

cat ~/.config/rofi/nerd-font-cheatsheet.txt | rofi -i -dmenu -font "Fira Code Nerd Font 15" -p "NF Cheatsheet" -fg "#ffffff" -width 30 | cut -d" " -f1 | tr '\n' ' ' | sed 's/⠀//g; s/\s//g' | xclip -selection clipboard
