#!/bin/bash

speaker="output:hdmi-stereo-extra1"

#Output Audio Device
check=$(pacmd list-cards | grep "<$speaker>")

if [ "$1" == "status" ];then
	[ "$check" == "" ] && echo " " || echo "蓼 "
	exit
fi

if [ "$1" == "pavu" ];then
	[ -z $(pgrep pavucontrol) ] && i3-msg exec pavucontrol || wmctrl -x -R pavucontrol 
	exit
fi

if [ "$check" == "" ];then
	notify-send "Switching to Speakers"
	pactl set-card-profile 0 $speaker
	pactl set-card-profile 1 off
else
	notify-send "Switching to Headset"
	pactl set-card-profile 0 off
	pactl set-card-profile 1 output:analog-stereo+input:analog-stereo
fi



#Updates Polybar's volume module
#if [[ -z $(pgrep polybar) ]]; then
#	polybar -r top &
#else
#	killall polybar 
#	polybar -r top &
#fi
