#!/bin/bash

#For this to work you need to:
#	- Set pywal.rasi as a theme in rofi
#	- Install the Vimix grub theme once
#	- Install slick greeter and add theme-name=pywal-oomox and background=/etc/lightdm/background.png to /etc/lightdm/slick-greeter.conf 

NC='\033[0m' # No Color
ACCENT='\033[1;31m'

while getopts i:a:s:b:gph flag
do
    case "${flag}" in
        i) path=${OPTARG};;
        a) opacity=${OPTARG};;
		s) saturation=${OPTARG};;
		b) backend=${OPTARG};;
		g) grub="True";;
		p) persistent="True";;
		h) help="True";;
    esac
done

if [[ "$help" == "True" ]]; then
	echo "usage: pywal [-i "/path/to/img.jpg"] [-a "alpha"] [-p] [-g] [-h] 

pywal - Makes wal changes persistent and changes other aspect of the system.

optional arguments:
  -h, --help          Show this help message and exit
  -a "alpha"            Set terminal background transparency. *Only works in URxvt*
  -g grub-theme       Applies this wallpaper to the Vimix Grub theme and installs it
  -p 		      Makes the changes on persistent by modifying .Xresources using ~/.config/wal/templates/colors.Xresources
"
else
	error_flag=False

	if ! [[ -z $path ]] && ! [[ -z $opacity ]] && ! [[ -z $saturation ]] && ! [[ -z $backend ]]; then
		wal -i $path -a $opacity --saturate $saturation --backend $backend

	elif ! [[ -z $path ]] && ! [[ -z $opacity ]] && ! [[ -z $backend ]]; then
		wal -i $path -a $opacity --backend $backend

	elif ! [[ -z $path ]] && ! [[ -z $saturation ]] && ! [[ -z $backend ]]; then
		wal -i $path --saturate $saturation --backend $backend

	elif ! [[ -z $path ]] && ! [[ -z $opacity ]] && ! [[ -z $saturation ]]; then
		wal -i $path -a $opacity --saturate $saturation

	elif ! [[ -z $path ]] && ! [[ -z $opacity ]]; then
		wal -i $path -a $opacity 

	elif ! [[ -z $path ]] && ! [[ -z $saturation ]]; then
		wal -i $path --saturate $saturation

	elif ! [[ -z $path ]] && ! [[ -z $backend ]]; then
		wal -i $path --backend $backend

	elif ! [[ -z $path ]]; then
		wal -i $path

	else
		error_flag=True
		echo "No path to the wallpaper has been set."
	fi
	exit_code=$?
	

	
	if [[ "$error_flag" == "False" ]] && [[ $exit_code -eq 0 ]]; then

		#Creates/Replaces pywal-oomox theme in .themes (it has to be applied in lxappearance once)
		sudo /opt/oomox/plugins/theme_oomox/gtk-theme/change_color.sh $HOME/.cache/wal/colors-oomox -o pywal-oomox -t $HOME/.themes >/dev/null && echo -e "\n${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: GTK+ Theme."
		
		#Replaces .Xresources with pywal's version and refreshes it if -p is set
		[[ "$persistent" == "True" ]] && sudo cat "$HOME/.cache/wal/colors.Xresources" > $HOME/.Xresources && sudo xrdb $HOME/.Xresources && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Xresources colors."

		#Updates Spicetify based on Xresources
		[[ "$persistent" == "True" ]] && spicetify update >/dev/null && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Spicetify Theme." && ! [[ -z $(pgrep spotify) ]] && killall spotify && i3-msg exec spotify >/dev/null
		
		#Adds pywal.rasi in rofi themes or overwrites existing one
		sudo cp $HOME/.cache/wal/colors-rofi-dark.rasi /usr/share/rofi/themes/pywal.rasi && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Rofi Theme."

		#Update grub theme and applies it if -g is present
		wal_path=$(cat $HOME/.cache/wal/wal)
		[[ "$grub" == "True" ]] && magick convert $wal_path -set colorspace RGB /usr/share/grub/themes/Vimix/background.png && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Grub's Background."

		#Update slick-greeter wallpaper
		sudo magick convert $wal_path /usr/share/slick-greeter/slick-greeter.png && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Slick-greeter's background."
		
		#Reload Dunst
		killall dunst
		i3-msg restart >/dev/null && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Reloaded${NC}: i3.\n"

		#Sets RGB
		sudo g213-led -a $(bash -c "sed -n '2p' $HOME/.cache/wal/colors | sed 's/#//'")
		sudo cm-rgb-cli set fan --brightness=5 --color=$(bash -c "sed -n '2p' $HOME/.cache/wal/colors | sed 's/#//'") logo --brightness=5 --color=$(bash -c "sed -n '7p' $HOME/.cache/wal/colors | sed 's/#//'")
		sudo $HOME/scripts/msi-rgb/target/release/msi-rgb 0 0 0 -x
		#Display colorscheme again
		wal --preview

	fi
fi