#!/bin/bash

#For this to work you need to:
#	- Set pywal.rasi as a theme in rofi
#	- Install the Vimix grub theme once
#	- Install slick greeter and add theme-name=pywal-oomox and background=/etc/lightdm/background.png to /etc/lightdm/slick-greeter.conf 

NC='\033[0m' # No Color
ACCENT='\033[1;31m'

while getopts i:a:gph flag
do
    case "${flag}" in
        i) path=${OPTARG};;
        a) opacity=${OPTARG};;
		g) grub="True";;
		p) persistent="True";;
		h) help="True";;
    esac
done

if [[ "$help" == "True" ]]; then
	echo "usage: pywal [-i "/path/to/img.jpg"] [-a "alpha"] [-p] [-g] [-h] 

pywal - Makes wal changes persistent and changes other aspect of the system.

optional arguments:
  -h, --help          Show this help message and exit
  -a "alpha"            Set terminal background transparency. *Only works in URxvt*
  -g grub-theme       Applies this wallpaper to the Vimix Grub theme and installs it
  -p 		      Makes the changes on persistent by modifying .Xresources using ~/.config/wal/templates/colors.Xresources
"
else
	error_flag=False

	if [[ -z $path ]] && [[ -z $opacity ]]; then
		error_flag=True
		echo "Specify the path to the wallpaper with -i and opacity with -a. "
	elif [[ -z $opacity ]]; then
		wal -i $path
	elif [[ -z $path ]]; then
		error_flag=True
		echo "No path to the wallpaper has been set."
	else
		wal -i $path -a $opacity
	fi

	exit_code=$?

	if [[ "$error_flag" == "False" ]] && [[ $exit_code -eq 0 ]]; then

		#Creates/Replaces pywal-oomox theme in .themes (it has to be applied in lxappearance once)
		sudo /opt/oomox/plugins/theme_oomox/gtk-theme/change_color.sh $HOME/.cache/wal/colors-oomox -o pywal-oomox -t $HOME/.themes && echo -e "\n${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: GTK+ Theme."
		#sudo /opt/oomox/plugins/oomoxify/oomoxify.sh $HOME/.cache/wal/colors-oomox
		
		#Replaces .Xresources with pywal's version and refreshes it if -p is set
		[[ "$persistent" == "True" ]] && sudo mv $HOME/.cache/wal/colors.Xresources ~/.Xresources && sudo xrdb $HOME/.Xresources && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Xresources colors."

		#Adds pywal.rasi in rofi themes or overwrites existing one
		sudo cp $HOME/.cache/wal/colors-rofi-dark.rasi /usr/share/rofi/themes/pywal.rasi && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Rofi Theme."

		#Update grub theme and applies it if -g is present
		wal_path=$(cat $HOME/.cache/wal/wal)
		[[ "$grub" == "True" ]] && magick convert $wal_path -set colorspace RGB /usr/share/grub/themes/Vimix/background.png && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Grub's Background."

		#Update slick-greeter wallpaper
		sudo magick convert $wal_path /usr/share/slick-greeter/slick-greeter.png && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Updated${NC}: Slick-greeter's background."
		
		#Reload Dunst
		killall dunst
		i3-msg restart 1>/dev/null && echo -e "${NC}[${ACCENT}I${NC}] ${ACCENT}Reloaded${NC}: i3.\n"

	fi
fi