#!/bin/bash

check=$(pacmd list-cards | grep "<output:hdmi-stereo-extra1>")

if [ "$check" == "" ] ;then
	echo "Switching to Speakers"
	notify-send "Switching to Speakers"
	pactl set-card-profile 0 output:hdmi-stereo-extra1
	pactl set-card-profile 1 off
else
	echo "Switching to Headset"
	notify-send "Switching to Headset"
	pactl set-card-profile 0 off
	pactl set-card-profile 1 output:analog-stereo
fi

#Updates Polybar's volume module
if [[ -z $(pgrep polybar) ]]; then
	polybar -r top &
else
	killall polybar 
	polybar -r top &
fi
